#!/bin/bash
#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

set -e
set -o pipefail

SCRIPT_NAME=$(basename $0)
WORK_DIR=/etc/apache2

usage() {
    set +x
    echo "$SCRIPT_NAME <site_name>[.conf]"
    echo
    if [ "$SCRIPT_NAME" == a2dissite ]; then
        echo "Disable Apache2 site configuration by removing a symlink"
        echo "${WORK_DIR}/sites-enabled/<site_name>.conf"
    else
        echo "Enable Apache2 site configuration by creating a symlink"
        echo "from ${WORK_DIR}/sites-available/<site_name>.conf"
        echo "to ${WORK_DIR}/sites-enabled/<site_name>.conf"
    fi
}

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

SITE_NAME=$(basename ${1%.conf})
SITE_ENABLED=${WORK_DIR}/sites-enabled/${SITE_NAME}.conf
SITE_AVAILABLE=${WORK_DIR}/sites-available/${SITE_NAME}.conf

if ! [ -e ${SITE_AVAILABLE} ]; then
    echo "ERROR: configuration file ${SITE_AVAILABLE} not found"
    exit 1
fi

if [ "$SCRIPT_NAME" == a2dissite ]; then
    if [ -e ${SITE_ENABLED} ]; then
        if [ -h ${SITE_ENABLED} ]; then
            rm ${SITE_ENABLED}
            echo "Site ${SITE_NAME} disabled."
            echo "To activate the new configuration, you need to run:"
            echo "  service apache2 reload"
            exit 0
        else
            echo "ERROR: found ${SITE_ENABLED} and it is not a symlink, giving up"
            exit 1
        fi
    else
        echo "Site ${SITE_NAME} already disabled"
        exit 0
    fi
else
    if [ -e ${SITE_ENABLED} ]; then
        if [ -h ${SITE_ENABLED} ]; then
            echo "Site ${SITE_NAME} already enabled"
            exit 0
        else
            echo "ERROR: found ${SITE_ENABLED} and it is not a symlink, giving up"
            exit 1
        fi
    else
        cd ${WORK_DIR}/sites-enabled
        ln -s ../sites-available/${SITE_NAME}.conf ${SITE_NAME}.conf
        echo "Site ${SITE_NAME} enabled."
        echo "To activate the new configuration, you need to run:"
        echo "  service apache2 reload"
        exit 0
    fi
fi