#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Apache2 global conf
---
- name: FND-AP2 | configure | Disable default port listeners
  become: yes
  replace:
    dest: "{{ apache2_listen_conf }}"
    regexp: '^((?!#).)*(Listen[ ]+.*)' # noqa
    replace: '# \2'
  register: ardana_notify_apache2_restart_required

# This matches the keystone status play, that we use to check that
# keystone comes up.
- name: FND-AP2 | configure | Increase timeout
  become: yes
  lineinfile:
    line: "Timeout {{ apache2_timeout }}"
    regexp: "^Timeout [0-9]+"
    dest: "{{ apache2_global_conf }}"
    state: present
  register: ardana_notify_apache2_reload_required

- name: FND-AP2 | configure | Debian - Set loglevel
  become: yes
  lineinfile:
    line: "LogLevel {{ apache2_loglevel }}"
    regexp: "^LogLevel"
    dest: "/etc/apache2/apache2.conf"
    state: present
  register: ardana_notify_apache2_reload_required
  when: ansible_os_family == 'Debian'

- name: FND-AP2 | configure | Suse - Set loglevel
  become: yes
  lineinfile:
    line: 'APACHE_LOGLEVEL="{{ apache2_loglevel }}"'
    regexp: "^APACHE_LOGLEVEL=.*"
    dest: /etc/sysconfig/apache2
    state: present
  register: ardana_notify_apache2_reload_required
  when: ansible_os_family == 'Suse'

# Apache2 modules

# These lines are a workaround for apache problem
# identified in KEYSTONE-297
- name:  FND-AP2 | configure | Debian - disable mpm_event
  become: yes
  apache2_module:
    name: mpm_event
    state: absent
  register: ardana_notify_apache2_restart_required
  when: ansible_os_family == 'Debian'

- name:  FND-AP2 | configure | Debian - enable mpm_worker
  become: yes
  apache2_module:
    name: mpm_worker
    state: present
  register: ardana_notify_apache2_restart_required
  when: ansible_os_family == 'Debian'

- name: FND-AP2 | configure | Suse - switch to mpm_worker
  become: yes
  lineinfile:
    line: 'APACHE_MPM="worker"'
    regexp: "^APACHE_MPM=.*"
    dest: /etc/sysconfig/apache2
    state: present
  register: ardana_notify_apache2_reload_required
  when: ansible_os_family == 'Suse'

# Suse may have proxy_http module listed before proxy. This causes errors
# while loading modules
- name:  FND-AP2 | configure | Suse - check proxy module load order
  become: yes
  shell: |
    grep -E 'proxy_http .*proxy' /etc/sysconfig/apache2 \
    && a2dismod proxy_http \
    || true
  args:
    executable: /bin/bash
  when: ansible_os_family == 'Suse'

# apache_module does not set 'changed' attribute correctly under Suse, because
# a2enmod output format differs from Debian version
- name:  FND-AP2 | configure | Enable apache modules
  become: yes
  shell_changed_regexp:
    command: "a2enmod {{ item }}"
    unchanged_regexp: " already "
  with_items: apache2_modules
  register: ardana_notify_apache2_restart_required

# Update config for mpm_worker
- name: FND-AP2 | configure | Debian - set MaxRequestWorkers
  become: yes
  lineinfile:
    line: "\tMaxRequestWorkers {{ max_request_workers }}"
    regexp: "MaxRequestWorkers"
    dest: "/etc/apache2/mods-available/mpm_worker.conf"
    state: present
  register: ardana_notify_apache2_reload_required
  when: ansible_os_family == 'Debian'

- name: FND-AP2 | configure | Suse - set MaxClients
  become: yes
  replace:
    replace: "\tMaxClients          {{ max_request_workers }}"
    regexp: "^\\s*MaxClients\\s+[0-9]+$"
    dest: "/etc/apache2/server-tuning.conf"
  register: ardana_notify_apache2_reload_required
  when: ansible_os_family == 'Suse'

# Apache sites
- name: FND-AP2 | configure | Debian - disable the default sites
  become: yes
  shell_changed_regexp:
    command: "a2dissite {{ item }}"
    unchanged_regexp: " already "
  with_items:
    - 000-default
    - default-ssl
  register: ardana_notify_apache2_restart_required
  when: ansible_os_family == 'Debian'

- name: FND-AP2 | configure | Suse - disable the default site
  become: yes
  lineinfile:
    line: '# Include /etc/apache2/default-server.conf'
    regexp: '^#?\s*Include\s+/etc/apache2/default-server\.conf'
    dest: /etc/apache2/httpd.conf
    state: present
  register: ardana_notify_apache2_reload_required
  when: ansible_os_family == 'Suse'

- name: FND-AP2 | configure | Suse - include conf files in conf.d
  become: yes
  lineinfile:
    line: 'IncludeOptional /etc/apache2/conf.d/*.conf'
    regexp: '^\s*IncludeOptional\s+/etc/apache2/conf\.d/\*\.conf'
    dest: /etc/apache2/httpd.conf
    state: present
  register: ardana_notify_apache2_reload_required
  when: ansible_os_family == 'Suse'

- name: FND-AP2 | configure | Suse - set default site permissions
  become: yes
  template:
    dest: /etc/apache2/conf.d/default.conf
    src: suse-default.conf.j2
    mode: 0644
  register: ardana_notify_apache2_reload_required
  when: ansible_os_family == 'Suse'

- name: FND-AP2 | configure | Add any sites to be enabled
  become: yes
  template:
    dest: "{{ apache2_vhost_dir }}/{{ item.key }}"
    src: sites-enabled.conf.j2
    mode: 0644
  with_dict: FND_AP2_sites_enabled | default({})
  register: ardana_notify_apache2_restart_required

- name: FND-AP2 | configure | enable sites
  become: yes
  shell_changed_regexp:
    command: a2ensite "{{ item.key }}"
    unchanged_regexp: " already "
  register: ardana_notify_apache2_restart_required
  with_dict: FND_AP2_sites_enabled | default({})
  when: ansible_os_family == 'Debian'
